[package]
name = "lcpget"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0"
ureq = "2"
zip = "0.5"
lcp-types = {path = "../lcp-types"}